apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: Linkerd
    category: ContainerApplication
    version: 2.7.1
    dependentOnVendorService: EKS
# Specification
spec: 
  preRun:
    stages:
      - name: InstallLinkerd
        command: |
            cd $TILE_HOME
            kubectl apply -f lib/install.yaml

            # Info
            kubectl get ns
            kubectl get deploy -n linkerd
            kubectl get pods -n linkerd
            kubectl get svc -n linkerd
  inputs:
    # String
    - name: clusterName
      inputType: String
      require: true
    # String
    - name: masterRoleARN
      inputType: String
      require: true

  # manifests:
  #   # Type of manifest
  #   manifestType: helm
  #   namespace: istio-system 
  #   # manifest folder
  #   folders:
  #     - k8s

          
  # Ouptputs represnt output value after launched, for 'ContainerApplication' might need leverage specific command to retrive output.
  outputs:
    # String
    - name: installedNamespace
      outputType: String
      defaultValue: linkerd
      description: Custom::String


  notes: []

