apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: Argocd0
    # Category: network, compute, container, storage, database, appliaction, analysis, ml
    category: appliaction
    version: 1.5.2
spec:
  dependencies:
    - name: eks
      tileReference: Eks0
      tileVersion: 0.0.1
  inputs:
    # string
    - name: clusterName
      inputType: string
      dependencies:
        - name: eks
          field: clusterName
      require: true
    # string
    - name: masterRoleARN
      inputType: string
      dependencies:
        - name: eks
          field: masterRoleARN
      require: true
    # number/ default: 2
    - name: namespace
      inputType: string
      require: false
      defaultValue: argocd
  
  manifests:
    # manifest: k8s / kustomization / helm 
    manifestType: k8s
    files:
      - k8s/install.yaml
    # folders:
    #   - k8s
          

  outputs:
    # string
    - name: user
      outputType: string
      defaultValue: admin
      description: Custom::User
    # string
    - name: password
      outputType: string
      defaultValueCommand: kubectl get pods -n {{.namespace}} -l app.kubernetes.io/name=argocd-server -o name | cut -d'/' -f 2
      description: Custom::Password        

  notes: []

