apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: Argocd0
    # Category: network, compute, container, storage, database, appliaction, analysis, ml
    category: appliaction
    version: 0.0.1
spec:
    inputs:
        # string
        - name: clusterName
          inputType: string
          depend:
            - tile: Eks0
              version: 0.0.1
              field: clusterName
          require: yes
        # string
        - name: masterRoleARN
          inputType: string
          require: yes
        # number/ default: 2
        - name: namespace
          inputType: string
          require: no
          defaultValue: argocd
        # manifest: k8s / kustomization / helm 
        - name: manifests
          type: k8s_manifest[]
          reuire: yes
          manifests:
            - k8s/install.yaml
          

    outputs:
        # string
        - name: adminUser
          outputType: string
          description: Custom::adminUser
        # string
        - name: adminPassword
          outputType: string
          description: Custom::adminPassword        

    notes: []

