apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: Istio0
    category: ContainerApplication
    version: 1.5.4
    dependentOnVendorService: EKS
# Specification
spec: 
  inputs:
    # String
    - name: clusterName
      inputType: String
      require: true
    # String
    - name: masterRoleARN
      inputType: String
      require: true


  #aws eks --region <region> update-kubeconfig --name <cluster> --role-arn <master role arn> --kubeconfig <config>
  manifests:
    # Type of manifest
    manifestType: K8s
    namespace: argocd 
    # manifest list
    files:
      - k8s/install.yaml
    # manifest folder
    # folders:
    #   - k8s
          
  # Ouptputs represnt output value after launched, for 'ContainerApplication' might need leverage specific command to retrive output.
  outputs:
    # String
    - name: installedNamespace
      outputType: String
      defaultValueCommand: echo $NAMESPACE
      description: Custom::User

  notes: []

