apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: Istio0
    category: ContainerApplication
    version: 1.5.4
    dependentOnVendorService: EKS
# Specification
spec: 
  preRun:
    stages:
      - name: InstallIstio1.6
        command: |
            kubectl apply -f lib/istio-operator-1.6.0.yaml

            # Create namespace for Istio
            kubectl create ns istio-system

            # Active Istio with demo profile
            kubectl apply -f - <<EOF
            apiVersion: install.istio.io/v1alpha1
            kind: IstioOperator
            metadata:
              namespace: istio-system
              name: istiocontrolplane
            spec:
              profile: demo
            EOF

            # Info
            kubectl get ns
            kubectl get pods -n istio-system
            kubectl get svc -n istio-system
  inputs:
    # String
    - name: clusterName
      inputType: String
      require: true
    # String
    - name: masterRoleARN
      inputType: String
      require: true

  # manifests:
  #   # Type of manifest
  #   manifestType: helm
  #   namespace: istio-system 
  #   # manifest folder
  #   folders:
  #     - k8s

          
  # Ouptputs represnt output value after launched, for 'ContainerApplication' might need leverage specific command to retrive output.
  outputs:
    # String
    - name: installedNamespace
      outputType: String
      defaultValueCommand: echo $NAMESPACE
      description: Custom::User

  notes: []

