apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: Go-Bumblebee-Jazz
    category: Application
    version: 0.7.1
spec:

  global:
    env:
      - name: GITHUB_USER
        value: cc4i
      - name: GIT_ACCESS_TOKEN
        value: $(self.inputs.gitAccessToken)
      - name: APP_REPO
        value: go-bumblebee
      - name: APP_BRANCH
        value: new-combo-jazz
      - name: APP_CONF_REPO
        value: go-bumblebee-jazz-config
      - name: KMS_KEY_ID
        value: $(self.inputs.kmsKeyID)

  preRun:
    stages:
      - name: CreateRepository
        command: |
          curl -H "Authorization: token $GIT_ACCESS_TOKEN" --data '{"name":"'$APP_CONF_REPO'", "private": true}' https://api.github.com/user/repos
      - name: SyncContentToRepository
        command: |
          cd $TILE_HOME
          git clone https://$GIT_ACCESS_TOKEN:x-oauth-basic@github.com/$GITHUB_USER/$APP_CONF_REPO.git
          cd $APP_CONF_REPO
          cp -r ../manifest/* .
          git add -A
          git commit -m "first commit"
          # git config --global user.email "robot@codebuild.aws"
          # git config --global user.name "robot"
          git push
      - name: CreateSecrets
        command: |
          cd $TILE_HOME/scripts
          ./create-secrets.sh github-bumblebee $GITHUB_USER $GIT_ACCESS_TOKEN $APP_CONF_REPO
      - name: RegisterAir2Codebuild
        command: |
          cd $TILE_HOME/scripts
          ./import-source-credential.sh
          ./create-iam-role.sh
          ./register-to-codebuild.sh
      - name: SetupDeploymentWithArgocd
        cammand: |
          cd $TILE_HOME/manifest/argocd
          ARGOCD_TOKEN=`curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/session -d $'{"username":"$(self.inputs.argocdUser)","password":"$(self.inputs.argocdPassword)"}'|jq -r '.token'`
          curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/applications -H "Authorization: Bearer $ARGOCD_TOKEN" -d "@stage-all-in-one.json"
          
          # add production cluster
          kubectl apply -f ./argocd-remote.yaml
          sed -i -e 's/__caData__/$(self.inputs.prodClusterCertificateAuthorityData)/g' ./add-cluster.json
          VALUE=$(echo $(self.inputs.prodClusterArn) | sed -e "s#/#\\\/#g")
          sed -i -e 's/__name__/'$VALUE'/g' ./add-cluster.json
          VALUE=$(echo $(self.inputs.prodClusterEndpoint) | sed -e "s#/#\\\/#g")
          sed -i -e 's/__server__/'$VALUE'/g' ./add-cluster.json
          curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/clusters -H "Authorization: Bearer $ARGOCD_TOKEN" -d "@add-cluster.json"
          
          # add production deployment
          VALUE=$(echo $(self.inputs.prodClusterEndpoint) | sed -e "s#/#\\\/#g")
          sed -i -e 's/__server__/'$VALUE'/g' ./production-all-in-one.json
          curl -s -k $(self.inputs.argocdBaseUrl)/api/v1/applications -H "Authorization: Bearer $ARGOCD_TOKEN" -d "@production-all-in-one.json"

  inputs:
    - name: gitAccessToken
      inputType: String
      require: true
    - name: kmsKeyID
      inputType: String
      require: true
    - name: argocdBaseUrl
      inputType: String
      require: true
    - name: argocdUser
      inputType: String
      require: true
    - name: argocdPassword
      inputType: String
      require: true
    - name: prodClusterCertificateAuthorityData
      inputType: String
      require: true
    - name: prodClusterArn
      inputType: String
      require: true
    - name: prodClusterEndpoint
      inputType: String
      require: true

  # Ouptputs represnt output value after launched, for 'ContainerApplication' might need leverage specific command to retrive output.
  outputs:
    # FromCommand
    - name: appConfRepo
      outputType: String
      defaultValueCommand: echo https://github.com/$GITHUB_USER/$APP_CONF_REPO.git
      description: Custom::GitHub        

  notes: []

