apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: Go-Bumblebee-Jazz
    category: Application
    version: 0.7.1
spec:

  global:
    env:
      - name: GITHUB_USER
        value: cc4i
      - name: GIT_ACCESS_TOKEN
        valueRef: $(self.inputs.gitAccessToken)
      - name: APP_REPO
        value: go-bumblebee
      - name: APP_BRANCH
        value: new-combo-jazz
      - name: APP_CONF_REPO
        value: go-bumblebee-jazz-config
      - name: KMS_KEY_ID
        valueRef: $(self.inputs.kmsKeyID)

  preRun:
    stages:
      - name: CreateRepository
        command: |
          curl -H "Authorization: token $GIT_ACCESS_TOKEN" --data '{"name":"'$APP_CONF_REPO'", "private": true}' https://api.github.com/user/repos
      - name: SyncContentToRepository
        command: |
          cd $TILE_HOME
          git clone https://$GIT_ACCESS_TOKEN:x-oauth-basic@github.com/$GITHUB_USER/$APP_CONF_REPO.git
          cd $APP_CONF_REPO
          cp -r ../manifest/* .
          git add -A
          git commit -m "first commit"
          # git config --global user.email "robot@codebuild.aws"
          # git config --global user.name "robot"
          git push
      - name: CreateSecrets
        command: |
          cd $TILE_HOME/scripts
          ./create-secrets.sh github-bumblebee $GITHUB_USER $GIT_ACCESS_TOKEN $APP_CONF_REPO
      - name: RegisterAir2Codebuild
        command: |
          cd $TILE_HOME/scripts
          ./import-source-credential.sh
          ./create-iam-role.sh
          ./register-to-codebuild.sh
  inputs:
    - name: gitAccessToken
      inputType: String
      require: true
    - name: kmsKeyID
      inputType: String
      require: true

          
  # Ouptputs represnt output value after launched, for 'ContainerApplication' might need leverage specific command to retrive output.
  outputs:
    # FromCommand
    - name: appConfRepo
      outputType: String
      defaultValueCommand: echo https://github.com/$GITHUB_USER/$APP_CONF_REPO.git
      description: Custom::GitHub        

  notes: []

