apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: argocd-with-app
spec:
  template:
    tiles:
      tileArgocd0152A:
        tileReference: Argocd0
        tileVersion: 1.5.2
        inputs:
          - name: cidr
            inputValue: 192.0.0.0/16        
          - name: clusterName
            inputValue: argocd-app-cluster2
          - name: capacity
            inputValue: 2
          - name: capacityInstance
            inputValue: m5.large
          - name: version
            inputValue: 1.16
        manifests:
          namespace: argocd

      goBumblebeeOnly001:
        tileReference: Go-Bumblebee-ONLY
        tileVersion: 0.0.1
        dependsOn: tileArgocd0152A
        inputs:
          - name: accessToken
            inputValue: <GITHUB TOKEN>
          - name: argocdNamespace
            inputValue: argocd

  summary:
      description: Argo CD has been installed in $clusterName with success and checking out following notes to get started.
      outputs:
        - name: EKS Cluster Name
          tileInstance: tileArgocd0152A
          outputValueRef: clusterName
        - name: Master role arn for EKS Cluster
          tileInstance: tileArgocd0152A
          outputValueRef: masterRoleARN
        - name: The API endpoint EKS Cluster
          tileInstance: tileArgocd0152A
          outputValueRef: clusterEndpoint
        - name: ArgoCD admin
          tileInstance: tileArgocd0152A
          outputValueRef: user
        - name: ArgoCD password
          tileInstance: tileArgocd0152A
          outputValueRef: password
        - name: Application Repository
          tileInstance: goBumblebeeOnly001
          outputValueRef: appRepo
        
      notes:
        - 1.Get all services information, 
        - |
          kubectl port-forward svc/argocd-server -n $NAMESPACE 8080:443
          kubectl port-forward svc/gateservice-external -n $APP_NAMESPACE 8080:443
        - 2. Push changes to GitRepo (https://github.com/$GITHUB_USER/$REPO_NAME.git) to to trigger automnated deployment
        - 3. Execute following commands to quick start,
        - |
          cd $WORK_HOME/lib/go-bumblebee-only/apps;./start-argocd.sh
        - |
          cd $WORK_HOME/lib/go-bumblebee-only/apps;./login-argocd.sh;create-app.sh
    