apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: mahjong
spec:
  template:
    category: ContainerProvider
    tiles:
      - tileReference: Eks0
        tileVersion: 0.0.1
        inputs:
          - name: clusterName
            inputValue: mahjong-cluster0
          - name: capacity
            inputValue: 2
          - name: capacityInstance
            inputValue: m5.large
          - name: version
            inputValue: 1.15


    
