apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: mahjong
spec:
  template:
    tiles:
      - tileReference: Go-Bumblebee
        tileVersion: 0.0.1
        inputs:
          - name: clusterName
            inputValue: mahjong-cluster0
          - name: masterRoleARN
            inputValue: <iam:role:arn>
          - name: accessToken
            inputValue: <github:access:token>
        manifests:
          namespace: go-bumblebee-new

    