apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: test
spec:
  template:
    tiles:
      tileGoBumblebeeJazz071:
        tileReference: Go-Bumblebee-Jazz
        tileVersion: 0.7.1
        inputs:
          - name: gitAccessToken
            inputValue:       

  summary:
      description: Testing.
      outputs:
        - name: gitRepo
          valueRef: $(tileGoBumblebeeJazz071.outputs.appConfRepo)

      notes: []
    