apiVersion: mahjong.io/v1alpha1
kind: Deployment 
metadata:
  name: go-bumblebee-jazz-application-demo
spec:
  template:
    tiles:
      # Generating master key
      tileAwsKmsKeyGenerator010:
        tileReference: AWS-KMS-KeyGenerator
        tileVersion: 0.1.0
        inputs:
          - name: symmetricKeyAlias
            inputValue: majhong/symmetric-key_0
          - name: asymmetricKeyAlias
            inputValue: majhong/asymmetric-key_0

      # ESK Cluster for Production
      tileEksWithSpotProd:
        tileReference: Eks-with-Spot
        tileVersion: 0.5.0
        inputs:
          - name: cidr
            inputValue: 192.0.0.0/16
          - name: clusterName
            inputValue: mahjong-spot-cluster0
          - name: clusterVersion
            inputValue: 1.16
          - name: keyPair4EC2
            inputValue: ore-keypair
          - name: capacityInstance
            inputValues: 
              - m5.large
              - r5.large
              - c5.large

      # EKS Cluster for Stage
      tileEksWithSpotStage:
        tileReference: Eks-with-Spot
        tileVersion: 0.5.0
        inputs:
          - name: cidr
            inputValue: 192.0.0.0/16
          - name: clusterName
            inputValue: mahjong-spot-cluster0
          - name: clusterVersion
            inputValue: 1.16
          - name: keyPair4EC2
            inputValue: ore-keypair
          - name: capacityInstance
            inputValues: 
              - m5.large
              - r5.large
              - c5.large
      
      # ElsatiCache Redis Cluster
      tileAWSElastiCacheRedis506Prod:
        tileReference: AWS-ElastiCache-Redis
        tileVersion: 5.0.6
        dependsOn: tileEksWithSpotProd
        inputs:
          - name: vpc
            # tileInstance.tileName.field
            inputValue: $cdk(tileEksWithSpotProd.Network0.baseVpc)     
          - name: subnetIds
            inputValues:
              - $cdk(tileEksWithSpotProd.Network0.privateSubnetId1)
              - $cdk(tileEksWithSpotProd.Network0.privateSubnetId2)
          - name: redisClusterName
            inputValue: redis-cluster-prod

      # ElsatiCache Redis Cluster
      tileAWSElastiCacheRedis506Stage:
        tileReference: AWS-ElastiCache-Redis
        tileVersion: 5.0.6
        dependsOn: tileEksWithSpotStage
        inputs:
          - name: vpc
            # tileInstance.tileName.field
            inputValue: $cdk(tileEksWithSpotStage.Network0.baseVpc)     
          - name: subnetIds
            inputValues:
              - $cdk(tileEksWithSpotStage.Network0.privateSubnetId1)
              - $cdk(tileEksWithSpotStage.Network0.privateSubnetId2)
          - name: redisClusterName
            inputValue: redis-cluster-stage

      # Istio 
      tileIstio0ForProduction:
        tileReference: Istio0
        tileVersion: 1.5.4
        inputs:
          - name: clusterName
            valueRef: $(tileEksWithSpotProd.outputs.clusterName)
          - name: masterRoleARN
            valueRef: $(tileEksWithSpotProd.outputs.masterRoleARN)
      tileIstio0ForStage:
        tileReference: Istio0
        tileVersion: 1.5.4
        inputs:
          - name: clusterName
            valueRef: $(tileEksWithSpotStage.outputs.clusterName)
          - name: masterRoleARN
            valueRef: $(tileEksWithSpotStage.outputs.masterRoleARN)
      
      # ArgoCD
      tileArgocdWithExsitingEks152:
        tileReference: Argocd-With-Existing-EKS
        tileVersion: 1.5.6
        dependsOn: tileEksWithSpotStage
        inputs:
          - name: clusterName
            valueRef: $(tileEksWithSpotStage.outputs.clusterName)         
          - name: masterRoleARN
            valueRef: $(tileEksWithSpotStage.outputs.masterRoleARN) 

      # Inject DEMO Applications & setup CI+CD
      tileGoBumblebeeJazz071:
        tileReference: Go-Bumblebee-Jazz
        tileVersion: 0.7.1
        inputs:
          - name: gitAccessToken
            inputValue: GITHUB-TOKEN
          - name: kmsKeyID
            valueRef: $(tileAwsKmsKeyGenerator010.outputs.symmetricKeyID)
          - name: argocdBaseUrl
            valueRef: $(tileArgocdWithExsitingEks152.outputs.argocdBaseUrl)
          - name: argocdUser
            valueRef: $(tileArgocdWithExsitingEks152.outputs.user)
          - name: argocdPassword
            valueRef: $(tileArgocdWithExsitingEks152.outputs.password)
          - name: prodClusterCertificateAuthorityData
            valueRef: $(tileEksWithSpotProd.outputs.clusterCertificateAuthorityData)
          - name: prodClusterArn
            valueRef: $(tileEksWithSpotProd.outputs.clusterArn)
          - name: prodClusterEndpoint
            valueRef: $(tileEksWithSpotProd.outputs.clusterEndpoint)
summary:
      description: |
        ++++++++++++++++++++++++++++++++++++++++++++++++++++
        +   Perfect Microservices with Demo Application    +
        ++++++++++++++++++++++++++++++++++++++++++++++++++++
      outputs:
        - name: EKS Cluster for Production
          valueRef: $(tileEksWithSpotProd.outputs.clusterName)
        - name: Master role for Production Cluster
          valueRef: $(tileEksWithSpotProd.outputs.masterRoleARN)
        - name: Endpoint for Production Cluster
          valueRef: $(tileEksWithSpotProd.outputs.clusterEndpoint)
        - name: EKS Cluster for Staging
          valueRef: $(tileEksWithSpotStage.outputs.clusterName)
        - name: Master role for Staging Cluster
          valueRef: $(tileEksWithSpotStage.outputs.masterRoleARN)
        - name: Endpoint for Staging Cluster
          valueRef: $(tileEksWithSpotStage.outputs.clusterEndpoint)
        - name: Endpoint for AgroCD
          valueRef: $(tileArgocdWithExsitingEks152.outputs.argocdBaseUrl)
        - name: Administrator for AgroCD
          valueRef: $(tileArgocdWithExsitingEks152.outputs.user)
        - name: Password for AgroCD Administrator
          valueRef: $(tileArgocdWithExsitingEks152.outputs.password)
        
      notes: []
 