apiVersion: mahjong.io/v1alpha1
kind: Tile
metadata:
    name: Argocd0
    version: 0.0.1
spec:
  #aws eks update-kubeconfig 
  # --name hello-eks 
  # --region us-west-2 
  # --role-arn arn:aws:iam::530820415924:role/Eks0Stack-eks0EksClusterMasterRole1E3A4E36-12A8X30PQB2BK
    inputs:
        # string
        - name: clusterName
          depend:
            - tile: Eks0
              version: 0.0.1
              field: clusterName
          require: yes
        # string
        - name: clusterName
          depend:
            - tile: Eks0
              version: 0.0.1
              field: clusterName
          require: yes
        # string
        - name: masterRoleARN
          require: yes
        # number/ default: 2
        - name: capacity
          require: no
        # string/ default: 'c5.large'
        - name: capacityInstance
          require: no
        # string/ default: '1.15'
        - name: version
          require: no

    outputs:
        # string/ type = CloudFormation type
        - name: clusterName
          type: AWS::EKS::Cluster.Name
        # string/ type = CloudFormation type
        - name: clusterEndpoint
          type: AWS::EKS::Cluster.Endpoint
        # string/ type = CloudFormation type
        - name: masterRoleARN
          type: AWS::IAM::Role.ARN
        # string/ type = Custome type if it's costomized output
        - name: kubectlConfigCommand
          type: Custom::kubectlConfigCommand

    notes:
      - "Tag public subnets with 'kubernetes.io/role/elb=1'"
      - "Tag priavte subnets with 'kubernetes.io/role/internal-elb=1'"

